# Generated by Django 4.1.13 on 2024-01-06 18:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='image_url',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='course_images/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.IntegerField(),
        ),
    ]
