# Generated by Django 4.1.13 on 2024-01-07 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_question_image_url_alter_question_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='image_url',
            field=models.ImageField(blank=True, upload_to='course_images/'),
        ),
    ]
