# Generated by Django 4.1.13 on 2024-01-07 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0003_alter_question_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='image_url',
            field=models.URLField(blank=True),
        ),
    ]
