# Generated by Django 4.1.13 on 2024-01-10 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0006_userscore'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='course',
        ),
        migrations.RemoveField(
            model_name='userscore',
            name='quiz_name',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
    ]
