# Generated by Django 4.1.13 on 2024-01-10 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0008_question_question_uuid_alter_question_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='question_uuid',
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
