# Generated by Django 4.1.13 on 2024-01-16 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0010_alter_question_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userscore',
            name='question',
        ),
    ]
