# Generated by Django 4.1.13 on 2024-02-05 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0012_alter_question_option_four_alter_question_option_one_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='option_four',
            field=models.CharField(blank=True, default=' ', max_length=100),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_one',
            field=models.CharField(blank=True, default=' ', max_length=100),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_three',
            field=models.CharField(blank=True, default=' ', max_length=100),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_two',
            field=models.CharField(blank=True, default=' ', max_length=100),
        ),
    ]
