# Generated by Django 4.1.13 on 2024-02-29 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0014_alter_question_option_four_alter_question_option_one_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
