# Generated by Django 4.1.13 on 2024-02-29 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0015_alter_question_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.CharField(max_length=255),
        ),
    ]
