# Generated by Django 4.1.13 on 2024-04-20 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0019_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Time',
        ),
        migrations.AddField(
            model_name='userscore',
            name='completion_time',
            field=models.IntegerField(default=2700),
        ),
    ]
