# Generated by Django 4.1.13 on 2024-04-20 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0020_delete_time_userscore_completion_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userscore',
            old_name='completion_time',
            new_name='time_taken',
        ),
        migrations.RemoveField(
            model_name='question',
            name='image_url',
        ),
    ]
