# Generated by Django 4.1.13 on 2024-04-14 18:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_otpvalidation_expired_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mail',
        ),
        migrations.AddField(
            model_name='otpvalidation',
            name='user_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='otpvalidation',
            name='otp',
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
