# Generated by Django 4.1.13 on 2024-04-20 15:37

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_delete_mail_otpvalidation_user_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpvalidation',
            name='user_email',
            field=models.EmailField(max_length=254, unique=True, validators=[user.models.validate_akgec_email]),
        ),
        migrations.AlterField(
            model_name='otpvalidation',
            name='user_name',
            field=models.CharField(max_length=30),
        ),
    ]
