# Generated by Django 4.1.13 on 2024-04-22 14:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_otpvalidation_user_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpvalidation',
            name='student_no',
            field=models.IntegerField(default=000000, unique=True),
            preserve_default=False,
        ),
    ]
